version: "3.8"
services:
  mysql-local:
    container_name: mysql-local
    image: mysql:latest
    deploy:
      replicas: 1
    env_file:
      - ../env/mysql.env
    volumes:
      - ../mysql/data:/var/lib/mysql
      - ../config/my.conf:/etc/mysql/conf.d/my.conf
    ports:
      - "13306:3306"
    restart: on-failure
  redis-local:
    container_name: redis-local
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    image: redis:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 128M
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    volumes:
      - ../config/redis.conf:/etc/redis/redis.conf
    ports:
      - "7000:6379"
    restart: on-failure
