server.port: 18081
spring.application.name: auth-service

spring.thymeleaf.cache: true # Whether to enable template caching.
spring.thymeleaf.check-template: true # Whether to check that the template exists before rendering it.
spring.thymeleaf.check-template-location: true # Whether to check that the templates location exists.
spring.thymeleaf.enabled: true # Whether to enable Thymeleaf view resolution for Web frameworks.
spring.thymeleaf.enable-spring-el-compiler: false # Enable the SpringEL compiler in SpringEL expressions.
spring.thymeleaf.encoding: UTF-8 # Template files encoding.
# spring.thymeleaf.excluded-view-names:  # Comma-separated list of view names (patterns allowed) that should be excluded from resolution.
spring.thymeleaf.mode: HTML # Template mode to be applied to templates. See also Thymeleaf's TemplateMode enum.
spring.thymeleaf.prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
# spring.thymeleaf.reactive.chunked-mode-view-names:  # Comma-separated list of view names (patterns allowed) that should be the only ones executed in CHUNKED mode when a max chunk size is set.
# spring.thymeleaf.reactive.full-mode-view-names:  # Comma-separated list of view names (patterns allowed) that should be executed in FULL mode even if a max chunk size is set.
spring.thymeleaf.reactive.max-chunk-size: 0 # Maximum size of data buffers used for writing to the response, in bytes.
# spring.thymeleaf.reactive.media-types: "application/json" # Media types supported by the view technology.
spring.thymeleaf.servlet.content-type: text/html # Content-Type value written to HTTP responses.
spring.thymeleaf.suffix: .html # Suffix that gets appended to view names when building a URL.

spring.security.user.name: test
spring.security.user.password: "123456"
